peps/SiteWeb/Models/Actif.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace SiteWeb.Models
{
    public class Actif
    {
        public static bool paramEstimes = false;
        public static bool rempli = false;
        public static Dictionary<string, Actif> mapNomActif { get; set; }

        public Actif()
        {
        }

        public Actif(int i, string n, string c)
        {
            id = i;
            nom = n;
            code = c;
            mapCoursDate = new SortedDictionary<DateTime, double>();
            mapNomActif.Add(c, this);
            correlation = new double[34];
        }

        [Key]
        public string code { get; set; }

        public int id { get; set; }

        public string nom { get; set; }

        public double quantité { get; set; }

        public double quantité_rebal { get; set; }

        public double variation_delta { get; set; }

        public double cours_courant { get; set; }

        public double volatilite { get; set; }

        public double[] correlation { get; set; }

        public SortedDictionary<DateTime, double> mapCoursDate { get; set; }

        public void ajouterCours(double cours, DateTime date)
        {
            mapCoursDate.Add(date, cours);
        }
    }
}

peps/SiteWeb/Controllers/ActifsController.cs
using SitePEPS.Controllers;
using SiteWeb.Models;
using SiteWeb.ViewModels;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SiteWeb.Controllers
{
    public class ActifsController : Controller
    {
        //
        // GET: /Actifs/
        public ActionResult Index()
        {
            HomeController.RecuperationDonnees();
            using (IDal dal = new Dal())
            {
                List<Kozei> fonds = dal.getAllKozei();
                SiteVM siteVM = new SiteVM(fonds[0],"", "", "current_page_item", "");
                siteVM.remplirListeActifs();
                ViewBag.ListeDesActifs = new SelectList(siteVM.listeActifs, "code", "nom", "DHR");
                return View(siteVM);
            }
        }

        

        public ActionResult GetSerie()
        {

            HomeController.RecuperationDonnees();
            string nomActif;
            using (IDal dal = new Dal())
            {
                List<Kozei> fonds = dal.getAllKozei();
                nomActif = fonds[0].nomActif;
            }
            var initial = new DateTime(1970, 1, 1);
            var date_cour = new DateTime(1970, 1, 1);
            var value = "";
            var result = "[";
            bool first = true;
            Actif a = Actif.mapNomActif[nomActif];
            foreach (KeyValuePair<DateTime, double> entry in a.mapCoursDate)
            {
                if (first)
                {
                    date_cour = entry.Key;
                    value = entry.Value.ToString(CultureInfo.GetCultureInfo("en-GB"));
                    double millisec = date_cour.ToUniversalTime().Subtract(initial).TotalMilliseconds;
                    result += "[" + millisec + "," + value + "]";
                    first = false;
                }
                else
                {
                    date_cour = entry.Key;
                    value = entry.Value.ToString(CultureInfo.GetCultureInfo("en-GB"));
                    double millisec = date_cour.Subtract(initial).TotalMilliseconds;
                    result += ",[" + millisec + "," + value + "]";
                }

            }
            result += "]";

            return Content(result, "application/json");
        }


        

        public ActionResult AfficherCours()
        {
            using (IDal dal = new Dal())
            {
                if (Request.HttpMethod == "POST")
                {
                    string nom = Request.Form["cd-dropdown"];
                    dal.modifierActifChoisi(1, nom);
                }
                return RedirectToAction("Index");
            }
        }
	}

    
}

peps/SiteWeb/Views/Actifs/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model SiteWeb.ViewModels.SiteVM
<script src="~/Scripts/modernizr.custom.63321.js"></script>

<div class="fleft">
    @using (Html.BeginForm("AfficherCours", "Actifs"))
    {
        
        @Html.DropDownList("cd-dropdown", (SelectList)ViewBag.ListeDesActifs, new { @class = "cd-select" })
        <input class="boutonListe" type="submit" value="Afficher le cours" />
    }
</div>

<div id="page">
    <div id="content">
        <div class="contentbg">
            <div class="post">
                <div class="entry">
                    <h2 class="title">Liste des actifs de votre Fonds</h2>
                    
                    </div>
                </div>
                <div>
                    <h3>@SiteWeb.Models.Actif.mapNomActif[@Model.k.nomActif].nom</h3>
                </div>
            <div style="clear: both;">&nbsp;</div>
            </div>
        <div style="clear: both;">&nbsp;</div>
        </div>

        <div style="clear: both;">&nbsp;</div>
 </div>


<div id="stockChart" style="height: 700px"></div>

<script type="text/javascript">
        $(document).ready(function () {
            chartInitialize("stockChart", '@Url.Action("GetSerie", "Actifs")');
        });
</script>

<script type="text/javascript" src="~/Scripts/jquery.dropdown.js"></script>
<script type="text/javascript">

    $(function () {

        $('#cd-dropdown').dropdown({
            gutter: 5,
            stack: false,
            delay: 100,
            slidingIn: 100
        });

    });

</script>