peps/SiteWeb/Controllers/PricingController.cs
using SitePEPS.Controllers;
using SiteWeb.Models;
using SiteWeb.ViewModels;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Wrapper;

using System.Text;
using APIFiMag;
using APIFiMag.Datas;
using APIFiMag.Importer;
using APIFiMag.Exporter;


namespace SiteWeb.Controllers
{
    public class PricingController : Controller
    {

        public ActionResult Index()
        {
            //Recuperation des cours et transformation en tableaux
            //pour pouvoir les passer en parametres d'une fonction du wrapper
            HomeController.RecuperationDonnees();
            int tailleCours = 0;
            foreach (KeyValuePair<string, Actif> entry in Actif.mapNomActif)
            {
                tailleCours += entry.Value.mapCoursDate.Count;
            }
            int[] codes = new int[tailleCours];
            int[][] dates = new int[tailleCours][];
            for (int i = 0; i < tailleCours; i++)
            {
                dates[i] = new int[3];
            }
            double[] cours = new double[tailleCours];
            int compt = 0;
            foreach (KeyValuePair<string, Actif> actif in Actif.mapNomActif)
            {
                foreach (KeyValuePair<DateTime, double> valeur in actif.Value.mapCoursDate)
                {
                    codes[compt] = actif.Value.id;
                    dates[compt][0] = valeur.Key.Day;
                    dates[compt][1] = valeur.Key.Month;
                    dates[compt][2] = valeur.Key.Year;
                    cours[compt] = valeur.Value;
                    compt++;
                }
            }

            //Recuperation des taux de change et transformation en tableaux
            //pour pouvoir les passer en parametres d'une fonction du wrapper
            HomeController.RecuperationTauxChange();
            int tailleTaux = 0;
            foreach (KeyValuePair<string, Devise> entry in Devise.mapNomDevise)
            {
                tailleTaux += entry.Value.mapTauxDate.Count;
            }
            int[] ids_taux = new int[tailleTaux];
            int[][] dates_taux = new int[tailleTaux][];
            for (int i = 0; i < tailleTaux; i++)
            {
                dates_taux[i] = new int[3];
            }
            double[] taux = new double[tailleTaux];
            int compteur = 0;
            foreach (KeyValuePair<string, Devise> devise in Devise.mapNomDevise)
            {
                foreach (KeyValuePair<DateTime, double> valeur in devise.Value.mapTauxDate)
                {
                    ids_taux[compteur] = devise.Value.id;
                    dates_taux[compteur][0] = valeur.Key.Day;
                    dates_taux[compteur][1] = valeur.Key.Month;
                    dates_taux[compteur][2] = valeur.Key.Year;
                    taux[compteur] = valeur.Value;
                    compteur++;
                }
            }

            DonneesDernierRebalancement lastData = new DonneesDernierRebalancement();

            double[] coursActifsCourants = new double[Kozei.nbActifsPlusDevise];
            double[] coursActifsDernierRebal = new double[Kozei.nbActifsPlusDevise];

            WrapperClass wrap = new WrapperClass();

            wrap.tailleCours = tailleCours;
            wrap.tailleTaux = tailleTaux;
            wrap.codes_cours = codes;
            wrap.dates_cours = dates;
            wrap.cours = cours;
            wrap.ids_taux = ids_taux;
            wrap.dates_taux = dates_taux;
            wrap.taux = taux;
            wrap.numJourDernierRebal = lastData.numJourDernierRebal;

            wrap.retrieveCoursActifs(coursActifsCourants, coursActifsDernierRebal);




            double produit_scal_delta_lastSpots = 0;
            for (int i = 0; i < Kozei.nbActifsPlusDevise; i++)
            {
                produit_scal_delta_lastSpots += lastData.delta[i] * coursActifsDernierRebal[i];
            }

            double val_pf = lastData.partSansRisque + produit_scal_delta_lastSpots;

            lastData.lastValPf = val_pf;
            Kozei.lastValPf = val_pf;



            // J'ai calculé mes parametres (volatilité, corrélation) maintenant je les stocke dans chaque Actif
            foreach (KeyValuePair<string, Actif> entry in Actif.mapNomActif)
            {
                entry.Value.cours_courant = coursActifsCourants[entry.Value.id - 1];
                entry.Value.quantité = lastData.delta[entry.Value.id - 1];
            }

            // chaque taux d'interet
            foreach (KeyValuePair<string, ActifSansRisqueEtranger> entry in ActifSansRisqueEtranger.mapNomActifSansRisqueEtranger)
            {
                entry.Value.cours = coursActifsCourants[Kozei.nbActifs + entry.Value.id - 1];
                entry.Value.quantité = lastData.delta[Kozei.nbActifs + entry.Value.id - 1];
            }

            using (IDal dal = new Dal())
            {
                SiteVM siteVM = new SiteVM("", "current_page_item", "", "");
                DateTime depart = new DateTime(2014, 7, 11);
                double nbJour = (double)lastData.numJourDernierRebal;
                // + 1 car on prend les cours de fermeture, on a les données jusqu'au jour nbJour, mais on est le jour nbJour + 1
                DateTime dateDernierRebal = depart.AddDays(nbJour+1);
                siteVM.jourDernierRebal = dateDernierRebal;
                return View(siteVM);
            }
        }


        public ActionResult Price()
        {
            //Recuperation des cours et transformation en tableaux
            //pour pouvoir les passer en parametres d'une fonction du wrapper
            HomeController.RecuperationDonnees();
            int tailleCours = 0;
            foreach (KeyValuePair<string, Actif> entry in Actif.mapNomActif)
            {
                tailleCours += entry.Value.mapCoursDate.Count;
            }
            int[] codes = new int[tailleCours];
            int[][] dates = new int[tailleCours][];
            for (int i = 0; i < tailleCours; i++)
            {
                dates[i] = new int[3];
            }
            double[] cours = new double[tailleCours];
            int compt = 0;
            foreach (KeyValuePair<string, Actif> actif in Actif.mapNomActif)
            {
                foreach (KeyValuePair<DateTime, double> valeur in actif.Value.mapCoursDate)
                {
                    codes[compt] = actif.Value.id;
                    dates[compt][0] = valeur.Key.Day;
                    dates[compt][1] = valeur.Key.Month;
                    dates[compt][2] = valeur.Key.Year;
                    cours[compt] = valeur.Value;
                    compt++;
                }
            }

            //Recuperation des taux de change et transformation en tableaux
            //pour pouvoir les passer en parametres d'une fonction du wrapper
            HomeController.RecuperationTauxChange();
            int tailleTaux = 0;
            foreach (KeyValuePair<string, Devise> entry in Devise.mapNomDevise)
            {
                tailleTaux += entry.Value.mapTauxDate.Count;
            }
            int[] ids_taux = new int[tailleTaux];
            int[][] dates_taux = new int[tailleTaux][];
            for (int i = 0; i < tailleTaux; i++)
            {
                dates_taux[i] = new int[3];
            }
            double[] taux = new double[tailleTaux];
            int compteur = 0;
            foreach (KeyValuePair<string, Devise> devise in Devise.mapNomDevise)
            {
                foreach (KeyValuePair<DateTime, double> valeur in devise.Value.mapTauxDate)
                {
                    ids_taux[compteur] = devise.Value.id;
                    dates_taux[compteur][0] = valeur.Key.Day;
                    dates_taux[compteur][1] = valeur.Key.Month;
                    dates_taux[compteur][2] = valeur.Key.Year;
                    taux[compteur] = valeur.Value;
                    compteur++;
                }
            }


            WrapperClass wrap = new WrapperClass();

            //creation de tableaux qui vont contenir les parametres 
            //estimés apres l'appel de la fonction CalculParam
            double[] vols = new double[Kozei.nbActifsPlusDevise];
            double[][] mat_corr = new double[Kozei.nbActifsPlusDevise][];
            for (int i = 0; i < Kozei.nbActifsPlusDevise; i++)
            {
                mat_corr[i] = new double[Kozei.nbActifsPlusDevise];
            }

            DonneesDernierRebalancement lastData = new DonneesDernierRebalancement();

            wrap.tailleCours = tailleCours;
            wrap.tailleTaux = tailleTaux;
            wrap.codes_cours = codes;
            wrap.dates_cours = dates;
            wrap.cours = cours;
            wrap.ids_taux = ids_taux;
            wrap.dates_taux = dates_taux;
            wrap.taux = taux;


            wrap.getEstimationParam(vols, mat_corr);
            Actif.paramEstimes = true;

            wrap.lastPartSansRisque = lastData.partSansRisque;
            wrap.lastPrice = lastData.lastPrice;
            wrap.lastDelta = lastData.delta;
            wrap.numJourDernierRebal = lastData.numJourDernierRebal;

            double[] coursActifs = new double[Kozei.nbActifsPlusDevise];

            wrap.calculPrice(vols, mat_corr, coursActifs);

            lastData.lastValPf = wrap.getLastValPf();
            Kozei.lastValPf = wrap.getLastValPf();

            DonneesNouveauPricing newData = new DonneesNouveauPricing();
            newData.newPrice = wrap.getPrice();
            newData.newIC = wrap.getIC();
            newData.newValPf = wrap.getNewValPf();


            // J'ai calculé mes parametres (volatilité, corrélation) maintenant je les stocke dans chaque Actif
            foreach (KeyValuePair<string, Actif> entry in Actif.mapNomActif)
            {

peps/SiteWeb/Views/Pricing/Couverture.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="page">
    <div id="content">
        <div class="contentbg">
            <div class="post">
                <div class="entry">
                    @if (@Model.message != null) { 
                        <div class="message">
                            @Model.message
                        </div>
                    }
                    <h2 class="title">Couverture de votre Fonds</h2>
                    <table class="table">
                        <thead class="titreTableau">
                            <tr>
                                <td></td>
                                <td>Prix du produit</td>
                                <td>Valeur du pf de couverture</td>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td class="titreTableau">Dernière connexion </br>
                                (@Model.jourDernierRebal.ToString("dd MMMM yyyy"))</td>
                                <td>@SiteWeb.Models.DonneesDernierRebalancement.lastData.lastPrice.ToString("0.0000")</td>
                                <td>@SiteWeb.Models.DonneesDernierRebalancement.lastData.lastValPf.ToString("0.0000")</td>
                            </tr>

                            <tr>
                                <td class="titreTableau">Aujourd'hui</td>
                                <td>
                                    @SiteWeb.Models.DonneesNouveauPricing.data.newPrice.ToString("0.0000")
                                </td>
                                <td>@SiteWeb.Models.DonneesNouveauPricing.data.newValPf.ToString("0.0000")</td>
                            </tr>
                        </tbody>
                    </table>
                </div>

                <h3>Voici la composition de votre portefeuille :</h3>
                <div class="texte">
                    La dernière colonne représente la potentielle nouvelle composition 
                    de votre portefeuille si vous souhaitez le rebalancer aujourd'hui. 
                    Si vous souhaitez sauvegarder cette nouvelle composition, cliquez 
                    sur le bouton prévu à cet effet en bas de cette page.
                </div>
                @using (Html.BeginForm("SauvegarderNouvelleCompo", "Pricing"))
                {
                    <input class="boutonSave" type="submit" value="Sauvegarder nouvelle composition" />
                }
                <table class="table table-striped">
                    <thead class="titreTableau">
                        <tr>
                            <td>Nom de l'actif</td>
                            <td>Cours</td>
                            <td>Quantité</td>
                            <td>Variation</td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in @SiteWeb.Models.Actif.mapNomActif.Values)
                        {
                            <tr>
                                <td class="titreTableau">@item.nom</td>
                                <td>@item.cours_courant.ToString("0.0000")</td>
                                <td>@item.quantité.ToString("0.0000")</td>
                                <td class ="red">@item.variation_delta.ToString("0.0000")</td>
                            </tr>
                        }
                        @foreach (var item in @SiteWeb.Models.ActifSansRisqueEtranger.mapNomActifSansRisqueEtranger.Values)
                        {
                            <tr>
                                <td class="titreTableau">@item.devise</td>
                                <td>@item.cours.ToString("0.0000")</td>
                                <td>@item.quantité.ToString("0.0000")</td>
                                <td class="red">@item.variation_delta.ToString("0.0000")</td>
                            </tr>
                        }
                    </tbody>
                </table>

                
            </div>
        </div>
    </div>
</div>
<div style="clear: both;">&nbsp;</div>

peps/SiteWeb/Views/Pricing/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="page">
    <div id="content">
        <div class="contentbg">
            <div class="post">
                <div class="entry">
                    <h2 class="title">Couverture de votre Fonds</h2>
                    @if (@Model.message != null)
                    {
                        <div class="message">
                            @Model.message
                        </div>
                    }
                    
                    @if (!@Model.coursRecuperes)
                    {
                        <form action="/Pricing/RecupData" method="post">
                            <input class="boutonRecupData" type="submit" value="Récupérer les données récentes" />
                        </form>
                        
                        @*<form action="/Pricing/NoRecup" method="post">
                            <input class="boutonSkip" type="submit" value="Passer cette étape" />
                        </form>*@
                    }
                   
                                      
                    <table class="table">
                        <thead class="titreTableau">
                            <tr>
                                <td></td>
                                <td>Prix théorique du produit</td>
                                <td>Valeur du pf de couverture</td>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td class="titreTableau">Dernière connexion </br>
                                (@Model.jourDernierRebal.ToString("dd MMMM yyyy"))</td>
                                <td>@SiteWeb.Models.DonneesDernierRebalancement.lastData.lastPrice.ToString("0.0000")</td>
                                <td>@SiteWeb.Models.DonneesDernierRebalancement.lastData.lastValPf.ToString("0.0000")</td>
                            </tr>
                        </tbody>
                    </table>

                    @if (@Model.coursRecuperes)
                    {
                        <form action="/Pricing/Price" method="post">
                            <input class="boutonPrice" type="submit" value="Pricer votre produit" />
                        </form>
                    }
                </div>

                <h3>Voici la composition de votre portefeuille :</h3>

                <table class="table table-striped">
                    <thead class="titreTableau">
                        <tr>
                            <td>Nom de l'actif</td>
                            <td>Cours</td>
                            <td>Quantité</td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in @SiteWeb.Models.Actif.mapNomActif.Values)
                        {
                            <tr>
                                <td class="titreTableau">@item.nom</td>
                                <td>@item.cours_courant.ToString("0.0000")</td>
                                <td>@item.quantité.ToString("0.0000")</td>
                            </tr>
                        }
                        @foreach (var item in @SiteWeb.Models.ActifSansRisqueEtranger.mapNomActifSansRisqueEtranger.Values)
                        {
                            <tr>
                                <td class="titreTableau">@item.devise</td>
                                <td>@item.cours.ToString("0.0000")</td>
                                <td>@item.quantité.ToString("0.0000")</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<div style="clear: both;">&nbsp;</div>

peps/SiteWeb/Views/Pricing/NouvelleCouverture.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="page">
    <div id="content">
        <div class="contentbg">
            <div class="post">
                <div class="entry">
                    <h2 class="title">Couverture de votre Fonds</h2>
                    @if (@Model.message != null)
                    {
                        <div class="message">
                            @Model.message
                        </div>
                    }

                    <table class="table">
                        <thead class="titreTableau">
                            <tr>
                                <td></td>
                                <td>Prix théorique du produit</td>
                                <td>Valeur du pf de couverture</td>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td class="titreTableau">Aujourd'hui </br>
                                (@Model.jourDernierRebal.ToString("dd MMMM yyyy"))</td>
                                <td>@SiteWeb.Models.DonneesNouveauPricing.data.newPrice.ToString("0.0000")</td>
                                <td>@SiteWeb.Models.DonneesNouveauPricing.data.newValPf.ToString("0.0000")</td>
                            </tr>
                        </tbody>
                    </table>

                </div>

                <h3>Voici la composition de votre portefeuille avec votre nouvelle couverture :</h3>

                <table class="table table-striped">
                    <thead class="titreTableau">
                        <tr>
                            <td>Nom de l'actif</td>
                            <td>Cours</td>
                            <td>Quantité</td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in @SiteWeb.Models.Actif.mapNomActif.Values)
                        {
                            <tr>
                                <td class="titreTableau">@item.nom</td>
                                <td>@item.cours_courant.ToString("0.0000")</td>
                                <td>@item.quantité_rebal.ToString("0.0000")</td>
                            </tr>
                        }
                        @foreach (var item in @SiteWeb.Models.ActifSansRisqueEtranger.mapNomActifSansRisqueEtranger.Values)
                        {
                            <tr>
                                <td class="titreTableau">@item.devise</td>
                                <td>@item.cours.ToString("0.0000")</td>
                                <td>@item.quantité_rebal.ToString("0.0000")</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<div style="clear: both;">&nbsp;</div>

peps/SiteWeb/Views/Pricing/Price.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="page">
    <div id="content">
        <div class="contentbg">
            <div class="post">
                <div class="entry">
                    <h2 class="title">Couverture de votre Fonds</h2>

                    <table class="table">
                        <thead class="titreTableau">
                            <tr>
                                <td></td>
                                <td>Prix théorique du produit</td>
                                <td>Valeur du pf de couverture</td>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td class="titreTableau">Dernière connexion </br>
                                (@Model.jourDernierRebal.ToString("dd MMMM yyyy"))</td>
                                <td>@SiteWeb.Models.DonneesDernierRebalancement.lastData.lastPrice.ToString("0.0000")</td>
                                <td>@SiteWeb.Models.DonneesDernierRebalancement.lastData.lastValPf.ToString("0.0000")</td>
                            </tr>

                            <tr>
                                <td class="titreTableau">Aujourd'hui</td>
                                <td>
                                    @SiteWeb.Models.DonneesNouveauPricing.data.newPrice.ToString("0.0000")
                                </td>
                                <td>@SiteWeb.Models.DonneesNouveauPricing.data.newValPf.ToString("0.0000")</td>
                            </tr>
                        </tbody>
                    </table>
                </div>

                <h3>Voici la composition de votre portefeuille :</h3>
                @using (Html.BeginForm("Rebalancer", "Pricing"))
                {
                    <input class="boutonRebalancement" type="submit" value="Rebalancer" />
                }

                <table class="table table-striped">
                    <thead class="titreTableau">
                        <tr>
                            <td>Nom de l'actif</td>
                            <td>Cours</td>
                            <td>Quantité</td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in @SiteWeb.Models.Actif.mapNomActif.Values)
                        {
                            <tr>
                                <td class="titreTableau">@item.nom</td>
                                <td>@item.cours_courant.ToString("0.0000")</td>
                                <td>@item.quantité.ToString("0.0000")</td>
                            </tr>
                        }
                        @foreach (var item in @SiteWeb.Models.ActifSansRisqueEtranger.mapNomActifSansRisqueEtranger.Values)
                        {
                            <tr>
                                <td class="titreTableau">@item.devise</td>
                                <td>@item.cours.ToString("0.0000")</td>
                                <td>@item.quantité.ToString("0.0000")</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<div style="clear: both;">&nbsp;</div>